### ISSUE TITLE
ModuleNotFoundError: No module named 'requests_toolbelt'

### ISSUE THREAD

**Issue by LakesideMiners** [SeanDaBlack/AbBOT#42]
when I run ```sudo python3 server.py```
I get the following traceback
```
Traceback (most recent call last):
  File "server.py", line 4, in <module>
    import forms
  File "/home/red/AbBOT/forms.py", line 2, in <module>
    from requests_toolbelt import MultipartEncoder
ModuleNotFoundError: No module named 'requests_toolbelt'
```
I'm running this in a venv. on Linux Mint

i got the same error even when running it without a venv

I have done ```pip3 install -r requirements.txt```
that outputs 

```
Requirement already satisfied: certifi==2021.5.30 in ./my_venv/lib/python3.8/site-packages (from -r requirements.txt (line 1)) (2021.5.30)
Requirement already satisfied: charset-normalizer==2.0.4 in ./my_venv/lib/python3.8/site-packages (from -r requirements.txt (line 2)) (2.0.4)
Requirement already satisfied: dnspython==2.1.0 in ./my_venv/lib/python3.8/site-packages (from -r requirements.txt (line 3)) (2.1.0)
Requirement already satisfied: idna==3.2 in ./my_venv/lib/python3.8/site-packages (from -r requirements.txt (line 4)) (3.2)
Requirement already satisfied: requests==2.26.0 in ./my_venv/lib/python3.8/site-packages (from -r requirements.txt (line 5)) (2.26.0)
Requirement already satisfied: requests-toolbelt==0.9.1 in ./my_venv/lib/python3.8/site-packages (from -r requirements.txt (line 6)) (0.9.1)
Requirement already satisfied: urllib3==1.26.6 in ./my_venv/lib/python3.8/site-packages (from -r requirements.txt (line 7)) (1.26.6)
```
I tried

```pip3 install requests-toolbelt```
and that outputted

```
Requirement already satisfied: requests-toolbelt in ./my_venv/lib/python3.8/site-packages (0.9.1)
Requirement already satisfied: requests<3.0.0,>=2.0.1 in ./my_venv/lib/python3.8/site-packages (from requests-toolbelt) (2.26.0)
Requirement already satisfied: idna<4,>=2.5; python_version >= "3" in ./my_venv/lib/python3.8/site-packages (from requests<3.0.0,>=2.0.1->requests-toolbelt) (3.2)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in ./my_venv/lib/python3.8/site-packages (from requests<3.0.0,>=2.0.1->requests-toolbelt) (1.26.6)
Requirement already satisfied: certifi>=2017.4.17 in ./my_venv/lib/python3.8/site-packages (from requests<3.0.0,>=2.0.1->requests-toolbelt) (2021.5.30)
Requirement already satisfied: charset-normalizer~=2.0.0; python_version >= "3" in ./my_venv/lib/python3.8/site-packages (from requests<3.0.0,>=2.0.1->requests-toolbelt) (2.0.4)
```
is this an issue with my system? Or somthing else?

**Comment by andria-dev** [comment]
You're likely not inside the `/home/red/AbBOT/` when you run the Python script. This will no longer be an issue soon though.

For now, just `cd /home/red/AbBOT/` and then run the script.

**Comment by LakesideMiners** [comment]
```
❯ pwd
/home/red/AbBOT
```
```
❯ sudo python3 server.py
Traceback (most recent call last):
  File "server.py", line 4, in <module>
    import forms
  File "/home/red/AbBOT/forms.py", line 2, in <module>
    from requests_toolbelt import MultipartEncoder
ModuleNotFoundError: No module named 'requests_toolbelt'
```

**Comment by coolgeek6667** [comment]
By any chance did you try `sudo pip3 install -r requirements.txt`?

**Comment by LakesideMiners** [comment]
that, fixed it, 
however, it hung at 
http://prolifewhistleblower.com:8000/
and going to it did not send me anywhere
