### ISSUE TITLE
KeyError: 'DEEP_AI_KEY'

### ISSUE THREAD

**Issue by MrMauricioLeite** [SeanDaBlack/AbBOT#48]
Getting this error after submitting my captcha. 
Here is my stack trace with verbose on:

```
AbBot git:(main) sudo python ./server.py -v
Starting the web server at http://prolifewhistleblower.com:8000/
Received POST data.
127.0.0.1 - - [03/Sep/2021 16:07:23] "POST / HTTP/1.1" 200 -
Got reCaptcha token!
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 51135)
Traceback (most recent call last):
  File "/Users/mleite/opt/anaconda3/lib/python3.7/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/Users/mleite/opt/anaconda3/lib/python3.7/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/Users/mleite/opt/anaconda3/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/Users/mleite/opt/anaconda3/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/Users/mleite/opt/anaconda3/lib/python3.7/http/server.py", line 426, in handle
    self.handle_one_request()
  File "/Users/mleite/opt/anaconda3/lib/python3.7/http/server.py", line 414, in handle_one_request
    method()
  File "./server.py", line 40, in do_POST
    forms.anonymous_form(token)
  File "/Users/mleite/AbBOT/forms.py", line 88, in anonymous_form
    generated_data = next(anonymous_form_data)
  File "/Users/mleite/AbBOT/data.py", line 222, in anonymous_form
    'textarea-1': get_tip_body(),
  File "/Users/mleite/AbBOT/data.py", line 242, in get_tip_body
    if os.environ[TEXT_GEN_API_VAR]:
  File "/Users/mleite/opt/anaconda3/lib/python3.7/os.py", line 678, in __getitem__
    raise KeyError(key) from None
KeyError: 'DEEP_AI_KEY'
----------------------------------------
Serving captcha.html
127.0.0.1 - - [03/Sep/2021 16:07:24] "GET /favicon.ico HTTP/1.1" 200 -
Received POST data.
127.0.0.1 - - [03/Sep/2021 16:08:03] "POST / HTTP/1.1" 200 -
Got reCaptcha token!
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 51354)
Traceback (most recent call last):
  File "/Users/mleite/opt/anaconda3/lib/python3.7/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/Users/mleite/opt/anaconda3/lib/python3.7/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/Users/mleite/opt/anaconda3/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/Users/mleite/opt/anaconda3/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/Users/mleite/opt/anaconda3/lib/python3.7/http/server.py", line 426, in handle
    self.handle_one_request()
  File "/Users/mleite/opt/anaconda3/lib/python3.7/http/server.py", line 414, in handle_one_request
    method()
  File "./server.py", line 40, in do_POST
    forms.anonymous_form(token)
  File "/Users/mleite/AbBOT/forms.py", line 88, in anonymous_form
    generated_data = next(anonymous_form_data)
StopIteration
----------------------------------------
Serving captcha.html
127.0.0.1 - - [03/Sep/2021 16:08:03] "GET /favicon.ico HTTP/1.1" 200 -

```

**Comment by MrMauricioLeite** [comment]
Oh, forget about it. I think my IP was blocked.
